name: CD-release

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-ci-release:
    runs-on: ubuntu-22.04

    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
        
    - name: Create application.yml and application-prod.yml
      run: | 
          mkdir src/main/resources
          cd src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./application.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yml

    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "websoso-fcm.json"
        json: ${{ secrets.WEBSOSOFCM_JSON }}
        dir: 'src/main/resources/'

    - name: Create apple login key file
      env:
        API_KEY: ${{ secrets.APPSTORE_API_KEY_ID }}
      run: |
        mkdir -p src/main/resources/static/apple
        echo "${{ secrets.APPLE_AUTH_KEY }}" > src/main/resources/static/apple/AuthKey_$API_KEY.p8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build -x test
      shell: bash

    - name: Docker build Setting
      uses: docker/setup-buildx-action@v2.9.1

    - name: Docker hub Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

    - name: Docker image Build and Push
      run: |
        docker build --platform linux/amd64 -t websoso/websoso-image .
        docker push websoso/websoso-image

  deploy-cd-release:
    needs: deploy-ci-release
    runs-on: ubuntu-22.04

    steps:
    - name: Run Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RELEASE_SERVER_IP }}
        username: ${{ secrets.RELEASE_SERVER_USER }}
        key: ${{ secrets.RELEASE_SERVER_KEY }}
        script: |
          cd ~
          ./deploy.sh
